[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self'; object-src 'none'"
    Cross-Origin-Opener-Policy = "unsafe-none"
    X-Frame-Options = "SAMEORIGIN"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
