[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "require-trusted-types-for 'script';"
    Cross-Origin-Opener-Policy = "unsafe-none"
    X-Frame-Options = "SAMEORIGIN"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
